name: push-to-acr
on:
  push:
    paths:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: ams0/acr-task-github-action@v1
        with:
          service_principal: ${{ secrets.service_principal }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.repository }}
          image: sample-python-flask-api
          # Omitted to clear a warning
          # git_access_token: ${{ secrets.git_access_token }}
          # Omitted; Build context for Docker; default to the root of the git repository
          # folder: ../../
          # Omitted; Path to the Dockerfile relative to folder; defaults to ./Dockerfile
          # dockerfile: ../../Dockerfile